### ISSUE TITLE
Make fragments replace the inner content

### ISSUE THREAD

**Issue by andreynovikov** [eldarion/eldarion-ajax#84]
This is the proposal. In many cases it would be more useful if fragments would replace the inner contents of the DOM element but not the element itself. Can you make it configurable globally or introduce some other AJAX data element, like 'fragments-inner'?

**Comment by paltman** [comment]
There is an `inner-fragments` option.

See https://github.com/eldarion/eldarion-ajax/blob/0.16.0/js/eldarion-ajax-handlers.js#L108

I realize the documentation could be improved around fragments.
