### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by nileshbits** [eldarion/eldarion-ajax#86]
Another great library Patrick! You should consider linking your old blog post http://paltman.com/twitter-bootstrap-and-ajax/ from the documentation - it is very good for forms. I particularly like the fact that I can use AJAX and not have to repeat server-side and client-side validation. It was starting to become a  real headache.

**Comment by paltman** [comment]
Thanks @nileshbits.  I finally added a list of blog posts to the README.
